import { ConversationData } from '@/types';

export const DEMO_CONVERSATIONS: ConversationData[] = [
  {
    id: 'demo-chatgpt-caching',
    title: 'Mastering Distributed Caching: Redis vs Memcached & Architecture Patterns',
    provider: 'chatgpt',
    url: 'https://chatgpt.com/share/672a91e5-8f40-800c-b5f7-cache-architecture',
    createdAt: '2026-09-08T10:15:00Z',
    messages: [
      {
        id: 'm1',
        role: 'user',
        content:
          'I am designing a high-throughput e-commerce platform that gets 100k requests/sec. We have huge database read bottlenecks during flash sales. Can you explain the best distributed caching strategies, compare Redis vs Memcached, and explain cache-aside vs write-through patterns? Please include code examples and eviction policies.'
      },
      {
        id: 'm2',
        role: 'assistant',
        content: [
          '### High-Throughput Distributed Caching Architecture',
          '',
          'When dealing with 100,000 requests per second during flash sales, relying directly on database queries (even with read replicas) will lead to connection saturation, lock contention, and high latencies. Distributed caching is essential to shield your primary database.',
          '',
          '---',
          '',
          '### 1. Redis vs. Memcached: Architectural Comparison',
          '',
          '| Feature | Redis | Memcached |',
          '| :--- | :--- | :--- |',
          '| **Data Structures** | Strings, Hashes, Lists, Sets, Sorted Sets, Bitmaps, Streams | Key-Value Strings only |',
          '| **Threading Model** | Single-threaded event loop (I/O multiplexing) | Multi-threaded (efficient on multi-core) |',
          '| **Persistence** | RDB snapshots & AOF logs | Pure in-memory (no persistence) |',
          '| **Pub/Sub & Lua** | Built-in Pub/Sub, Lua scripting, Transactions | None |',
          '| **Clustering** | Native Redis Cluster with automatic sharding | Client-side consistent hashing |',
          '',
          '**Recommendation**: For modern architectures, **Redis** is preferred because Sorted Sets allow rate-limiting and leaderboards, Hashes store structured cart items without full serialization, and persistence prevents cold-start cache stampedes.',
          '',
          '---',
          '',
          '### 2. Core Caching Patterns',
          '',
          '#### Pattern A: Cache-Aside (Lazy Loading)',
          'The application first queries the cache. If a **Cache Hit** occurs, data is returned immediately. If a **Cache Miss** occurs, the app reads from the database, writes the result to the cache, and returns it.',
          '',
          '```typescript',
          '// Production TypeScript Implementation: Cache-Aside Pattern',
          "import { Redis } from 'ioredis';",
          "import { Database } from './db';",
          '',
          'const redis = new Redis(process.env.REDIS_URL);',
          '',
          'interface Product {',
          '  id: string;',
          '  name: string;',
          '  price: number;',
          '  stock: number;',
          '}',
          '',
          'export async function getProduct(productId: string): Promise<Product> {',
          '  const cacheKey = "product:" + productId;',
          '',
          '  // 1. Attempt Cache Fetch',
          '  const cachedData = await redis.get(cacheKey);',
          '  if (cachedData) {',
          '    return JSON.parse(cachedData) as Product;',
          '  }',
          '',
          '  // 2. Cache Miss: Retrieve from Source Database',
          '  const product = await Database.query<Product>("SELECT * FROM products WHERE id = ?", [productId]);',
          '  ',
          '  if (product) {',
          '    await redis.setex(cacheKey, 900, JSON.stringify(product));',
          '  }',
          '',
          '  return product;',
          '}',
          '```',
          '',
          '#### Pattern B: Write-Through & Write-Behind',
          '- **Write-Through**: The application writes data to the cache, and the cache synchronously updates the database before acknowledging success.',
          '- **Write-Behind (Write-Back)**: Writes immediately to cache and acknowledges the user. An asynchronous worker flushes batched changes to the database.',
          '',
          '---',
          '',
          '### 3. Critical Flash-Sale Edge Cases',
          '',
          '1. **Cache Stampede (Thundering Herd)**: When a high-demand key expires during a flash sale, thousands of concurrent requests query the DB simultaneously. Fix with distributed locks or probabilistic early expiration.',
          '2. **Cache Penetration**: Malicious users request non-existent IDs. Fix by caching null values with short TTLs or using Bloom Filters.',
          '3. **Eviction Policy**: Configure Redis with maxmemory-policy allkeys-lru to retain active promotional inventory.'
        ].join('\n')
      }
    ]
  },
  {
    id: 'demo-gemini-multimodal',
    title: 'Google Gemini 2.0 Flash: Multimodal Streaming & 1M Context Window',
    provider: 'gemini',
    url: 'https://gemini.google.com/share/gemini-2-multimodal',
    createdAt: '2026-09-09T14:30:00Z',
    messages: [
      {
        id: 'g1',
        role: 'user',
        content:
          'Explain how Google Gemini handles native multimodal inputs (audio, video, text) compared to traditional pipeline architectures. How does the 1M+ token context window enable whole-codebase reasoning, and how do we build real-time audio streaming using the Gemini Live API?'
      },
      {
        id: 'g2',
        role: 'assistant',
        content: [
          '### Google Gemini 2.0: Native Multimodal Architecture',
          '',
          'Unlike older architectures that separate vision, speech recognition (Whisper), and text LLMs through discrete cascading stages, **Gemini was built natively multimodal from the ground up**. Audio, video, images, and text are tokenized into a unified multimodal latent space.',
          '',
          '---',
          '',
          '### 1. Unified Multimodal vs. Cascaded Pipelines',
          '',
          '| Metric | Cascaded Pipeline (Whisper + LLM + TTS) | Native Gemini Multimodal |',
          '| :--- | :--- | :--- |',
          '| **Latency** | High (800ms - 2500ms cumulative) | Real-time Bidirectional (< 250ms) |',
          '| **Tone & Emotion** | Lost in transcription step | Preserved (detects pitch, cadence, pauses) |',
          '| **Context Window** | Restricted to audio chunks | 1M to 2M unified tokens |',
          '| **Interruption Handling**| Awkward client-side cutoffs | Native full-duplex conversational barge-in |',
          '',
          '---',
          '',
          '### 2. Live Audio WebSocket Integration (Python SDK)',
          '',
          '```python',
          'import asyncio',
          'from google import genai',
          '',
          'client = genai.Client(api_key="GEMINI_API_KEY", http_options={"api_version": "v1alpha"})',
          '',
          'async def run_live_audio_session():',
          '    # Connect to Gemini Multimodal Live API via bidirectional WebSocket',
          '    async with client.aio.live.connect(model="gemini-2.0-flash-exp") as session:',
          '        print("Connected to Gemini 2.0 Live stream")',
          '        ',
          '        # Send raw audio PCM stream and receive real-time audio + text tokens',
          '        async for response in session.receive():',
          '            if response.server_content:',
          '                model_turn = response.server_content.model_turn',
          '                for part in model_turn.parts:',
          '                    if part.text:',
          '                        print(part.text, end="", flush=True)',
          '```',
          '',
          '---',
          '',
          '### 3. Key Takeaways for Production Deployments:',
          '- Use WebSockets for bidirectional voice streaming rather than chunked REST calls.',
          '- Leverage 1M+ context window for repository-wide AST parsing and dependency analysis.',
          '- Implement client-side VAD (Voice Activity Detection) to gracefully handle natural user interruptions.'
        ].join('\n')
      }
    ]
  },
  {
    id: 'demo-claude-artifacts',
    title: 'Anthropic Claude 3.7 Sonnet: Hybrid Extended Thinking & Agentic Tool Use',
    provider: 'claude',
    url: 'https://claude.ai/share/claude-3-7-sonnet-hybrid',
    createdAt: '2026-09-10T16:00:00Z',
    messages: [
      {
        id: 'c1',
        role: 'user',
        content:
          'What makes Claude 3.7 Sonnet unique with its hybrid extended thinking model? How do developers control the thinking budget, and how does Claude manage complex state transitions and artifacts compared to standard chain-of-thought?'
      },
      {
        id: 'c2',
        role: 'assistant',
        content: [
          '### Anthropic Claude 3.7 Sonnet: Hybrid Architecture',
          '',
          'Claude 3.7 Sonnet introduces a **hybrid reasoning model** allowing users and developers to dynamically control the depth of model deliberation. It can operate in high-speed responsive mode or deep analytical thinking mode.',
          '',
          '---',
          '',
          '### 1. Extended Thinking: Dynamic Token Budgeting',
          '',
          'Instead of being forced into fixed reasoning overhead, the `thinking` parameter allows precise allocation of computational depth:',
          '',
          '```typescript',
          'import Anthropic from "@anthropic-ai/sdk";',
          '',
          'const anthropic = new Anthropic();',
          '',
          'const response = await anthropic.messages.create({',
          '  model: "claude-3-7-sonnet-20250219",',
          '  max_tokens: 16000,',
          '  thinking: {',
          '    type: "enabled",',
          '    budget_tokens: 8000 // Allocates up to 8k tokens for rigorous internal verification',
          '  },',
          '  messages: [',
          '    { role: "user", content: "Audit this cryptographic zero-knowledge proof circuit for timing side-channels." }',
          '  ]',
          '});',
          '```',
          '',
          '---',
          '',
          '### 2. Core Architectural Advantages',
          '- **Steerable Latency vs. Reasoning Depth**: Budget tokens scale from 1,024 to 64,000 tokens depending on whether the task is a quick syntax check or a 10,000-line codebase refactor.',
          '- **Visible Thinking Trace**: Inspectable reasoning traces enable security auditing and guardrail verification.',
          '- **Seamless Tool Use with Reasoning**: Formulates tool calls midway through deliberation, inspects results, and continues reasoning iteratively.'
        ].join('\n')
      }
    ]
  }
];
